# Demo title
title: "Rovybot Demo"

inputs:
    input0:
        # Camera source.  /dev/video-tevs-cam0 is the forward-facing camera on the right
        source: /dev/video-tevs-cam0
        format: yuv
        width: 1280
        height: 720
        framerate: 30

models:
    model0:
        model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model1:
        model_path: /opt/model_zoo/TVM-OD-5120-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model2:
        model_path: /opt/model_zoo/ONR-OD-8200-yolox-nano-lite-mmdet-coco-416x416
        viz_threshold: 0.6
outputs:
    output0:
        sink: glimagesink
        width: 1280
        height: 800
    output1:
        sink: kmssink
        width: 1280
        height: 800
    output2:
        sink: waylandsink
        width: 1280
        height: 800
    output3:
        sink: fakesink
        width: 1280
        height: 800

flows:
    flow0: [input0,model2,output1,[0,0,640,400]]


