# Demo title
title: "EdgeAI Based Subject Tracking Demo"

inputs:
    input0:
        source: /dev/video-tevs-cam0
        format: yuv
        width: 1280
        height: 720
        framerate: 15
models:
    model0:
        model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model1:
        model_path: /opt/model_zoo/TVM-OD-5120-ssdLite-mobDet-DSP-coco-320x320
        viz_threshold: 0.6
    model2:
        model_path: /opt/model_zoo/TFL-OD-2010-ssd-mobV2-coco-mlperf-300x300
        viz_threshold: 0.6
outputs:
    output0:
        sink: waylandsink
        width: 1280
        height: 800
    output1:
        sink: kmssink
        width: 1920
        height: 1080

flows:
    flow0: [input0,model1,output0,[0,0,1280,720]]
